apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: __IMAGE_NAME__:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 3700
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-application
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3700
      targetPort: 3700