apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: my-application
spec:
  replicas: 2  # Augmentez le nombre de réplicas pour une meilleure disponibilité
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"  # Permet aux pods de s'exécuter sur le nœud de contrôle
      containers:
        - name: frontend
          image: __IMAGE_NAME__:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:  # Spécifiez les ressources pour le conteneur
            requests:
              memory: "256Mi"  # Mémoire demandée
              cpu: "250m"      # CPU demandé
            limits:
              memory: "512Mi"  # Limite de mémoire
              cpu: "500m"      # Limite de CPU
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-application
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000  # Ajoutez le port cible pour plus de clarté
  type: NodePort
