apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: my-application
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-vol
          mountPath: /data/mongo
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
           claimName: app-conf-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: my-application
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017