apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-conf
  namespace: my-application
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db