apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-conf-claim
  namespace: my-application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi